//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalSystemS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_tbl
    {
        public Admin_tbl()
        {
            this.Comp_Organ = new HashSet<Comp_Organ>();
            this.Student_tbl = new HashSet<Student_tbl>();
        }
    
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_password { get; set; }
    
        public virtual ICollection<Comp_Organ> Comp_Organ { get; set; }
        public virtual ICollection<Student_tbl> Student_tbl { get; set; }
    }
}
