//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalSystemS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicat_of_physiol
    {
        public int indicat_of_physiol_id { get; set; }
        public Nullable<decimal> Iheight { get; set; }
        public Nullable<decimal> Iweight { get; set; }
        public Nullable<decimal> Iogk { get; set; }
        public Nullable<decimal> IogkVd { get; set; }
        public Nullable<decimal> IogkVyd { get; set; }
        public Nullable<decimal> Izhi { get; set; }
        public Nullable<decimal> Ichss { get; set; }
        public Nullable<decimal> Iadsys { get; set; }
        public Nullable<decimal> Iaddias { get; set; }
        public Nullable<decimal> Izhel { get; set; }
        public Nullable<decimal> Ido { get; set; }
        public Nullable<decimal> Imod { get; set; }
        public Nullable<decimal> Ishtang { get; set; }
        public Nullable<decimal> Igenchi { get; set; }
        public Nullable<decimal> Ichp { get; set; }
        public Nullable<decimal> Iadaptp { get; set; }
        public Nullable<decimal> Impk { get; set; }
        public Nullable<decimal> Ipwc { get; set; }
        public Nullable<decimal> Ivremz { get; set; }
        public Nullable<decimal> Ikolnaklon { get; set; }
        public Nullable<decimal> Ipone { get; set; }
        public Nullable<decimal> Iptwo { get; set; }
        public Nullable<decimal> Ipthree { get; set; }
        public Nullable<int> Indicat_of_physiol_FK_Organ { get; set; }
        public Nullable<int> Indicat_of_physiol_FK_STU { get; set; }
        public Nullable<decimal> Irufie { get; set; }
        public Nullable<decimal> Iskibin { get; set; }
        public Nullable<decimal> Ishapal { get; set; }
        public Nullable<decimal> Irobinson { get; set; }
    
        public virtual Comp_Organ Comp_Organ { get; set; }
        public virtual Student_tbl Student_tbl { get; set; }
    }
}
