//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalSystemS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppraisalSysEntities : DbContext
    {
        public AppraisalSysEntities()
            : base("name=AppraisalSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_tbl> Admin_tbl { get; set; }
        public DbSet<Comp_Organ> Comp_Organ { get; set; }
        public DbSet<Indicat_of_physiol> Indicat_of_physiol { get; set; }
        public DbSet<Pedag_test> Pedag_test { get; set; }
        public DbSet<Student_tbl> Student_tbl { get; set; }
    }
}
